kstrwbry_dto:
    dto_definitions:
        Strategy:
            strategy_name: string
            stop_loss_condition: int
            indicators: array #'App\Kstrwbry\DtoBundle\Interfaces\DTOInterface[]'
        Indicator:
            indicator_name: string
            indicator: '\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface'
            indicatorConfig: array
            builder: '\App\EntityBuilder\EntityBuilderBase'
            prev_entity: '\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface|null'
            indicator_dependencies: array #'\App\DTO\IndicatorDTO'
        RVI:
            period: int
            lower_signal_line: int
            upper_signal_line: int
        RSI:
            period: int
            lower_signal_line: int
            upper_signal_line: int
        MACD:
            short_period: int
            long_period: int
            signal_period: int
        StdDev:
            period: int
