kstrwbry_dto:
    dto_definitions:
        Strategy:
            strategy_name: string
            stop_loss_condition: int
            indicators: array #'App\Kstrwbry\DtoBundle\Interfaces\DTOInterface[]'
        Indicator:
            indicator_name: string
            indicator: '\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface'
            indicatorConfig: array
            builder: '\App\EntityBuilder\EntityBuilderBase'
            prev_entity: '\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface|null'
            outdated_entity: '\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface|null'
            indicator_dependencies: array #'\App\DTO\IndicatorDTO'
        KlineRaw:
            run_index: int
            start_time: string
            start_time_date: \DateTime
            close_time: string
            close_time_date: \DateTime
            symbol: string
            interval: string
            first_trade_id: string
            last_trade_id: string
            open: string
            open_float: float
            close: string
            close_float: float
            high: string
            high_float: float
            low: string
            low_float: float
            base_asset_volume: string
            base_asset_volume_float: float
            trades_count: string
            trades_count_int: int
            is_closed: string
            is_closed_bool: bool
            quote_asset_volume: string
            quote_asset_volume_float: float
            taker_buy_base_asset_volume: string
            taker_buy_base_asset_volume_float: float
            taker_buy_quote_asset_volume: string
            taker_buy_quote_asset_volume_float: float
        RVI:
            period: int
            lower_signal_line: int
            upper_signal_line: int
        RSI:
            period: int
            lower_signal_line: int
            upper_signal_line: int
        MACD:
            short_period: int
            long_period: int
            signal_period: int
        StdDev:
            period: int
        exchangeInfo:
            symbol: string
            currentPrice: float
            minQty: float               # like 0.10000000 ADA
            stepSize: float             # like 0.10000000 ADA
            precision: int              # like 1 for ADA, 8 for BTC
            baseAsset: string           # like BTC or ADA
            quoteAsset: string          # like EUR or USDC
            baseAssetAvailable: float   # amount of BTC or ADA
            quoteAssetAvailable: float  # amount of EUR or USDC
            quantityToBuy: float        # calculated amount of ADA or BTC to buy
            quoteAssetToBuy: float      # calculated amount of ADA or BTC to buy in USDC or EUR
            quantityToSell: float       # amount of ADA or BTC to sell
            percentageToSpend: float
            lastBuyTradePrice: float
            lastSellTradePrice: float
