version: '3'
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-trader2}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-trader2}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###
  php:
      build: ./docker/php
      volumes:
          - ./:/var/www/html
          - ./docker/php/memory-limit.ini:/usr/local/etc/php/conf.d/memory-limit.ini
      environment:
          PHP_IDE_CONFIG: "serverName=symfony"
      extra_hosts:
          - "host.docker.internal:host-gateway"

  nginx:
      image: nginx:1.27-alpine
      volumes:
          - ./:/var/www/html
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
          - "8080:80"
      depends_on:
          - php

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
