<?php

/**
 * Generated by "dto:generate" command
 */

declare(strict_types=1);

namespace App\DTO;

class ExchangeinfoDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected string $symbol;
    protected float $currentPrice;
    protected float $minQty;
    protected float $stepSize;
    protected int $precision;
    protected string $baseAsset;
    protected string $quoteAsset;
    protected float $baseAssetAvailable;
    protected float $quoteAssetAvailable;
    protected float $quantityToBuy;
    protected float $quoteAssetToBuy;
    protected float $quantityToSell;
    protected float $percentageToSpend;
    protected float $lastBuyTradePrice;
    protected float $lastSellTradePrice;

    public function __construct(
        ?string $symbol = null,
        ?float $currentPrice = null,
        ?float $minQty = null,
        ?float $stepSize = null,
        ?int $precision = null,
        ?string $baseAsset = null,
        ?string $quoteAsset = null,
        ?float $baseAssetAvailable = null,
        ?float $quoteAssetAvailable = null,
        ?float $quantityToBuy = null,
        ?float $quoteAssetToBuy = null,
        ?float $quantityToSell = null,
        ?float $percentageToSpend = null,
        ?float $lastBuyTradePrice = null,
        ?float $lastSellTradePrice = null,
    ) {
        if ($symbol !== null) $this->symbol = $symbol;
        if ($currentPrice !== null) $this->currentPrice = $currentPrice;
        if ($minQty !== null) $this->minQty = $minQty;
        if ($stepSize !== null) $this->stepSize = $stepSize;
        if ($precision !== null) $this->precision = $precision;
        if ($baseAsset !== null) $this->baseAsset = $baseAsset;
        if ($quoteAsset !== null) $this->quoteAsset = $quoteAsset;
        if ($baseAssetAvailable !== null) $this->baseAssetAvailable = $baseAssetAvailable;
        if ($quoteAssetAvailable !== null) $this->quoteAssetAvailable = $quoteAssetAvailable;
        if ($quantityToBuy !== null) $this->quantityToBuy = $quantityToBuy;
        if ($quoteAssetToBuy !== null) $this->quoteAssetToBuy = $quoteAssetToBuy;
        if ($quantityToSell !== null) $this->quantityToSell = $quantityToSell;
        if ($percentageToSpend !== null) $this->percentageToSpend = $percentageToSpend;
        if ($lastBuyTradePrice !== null) $this->lastBuyTradePrice = $lastBuyTradePrice;
        if ($lastSellTradePrice !== null) $this->lastSellTradePrice = $lastSellTradePrice;
    }

    public function getSymbol(): string
    {
        return $this->symbol;
    }

    public function setSymbol(string $symbol): static
    {
        $this->symbol = $symbol;

        return $this;
    }

    public function getCurrentPrice(): float
    {
        return $this->currentPrice;
    }

    public function setCurrentPrice(float $currentPrice): static
    {
        $this->currentPrice = $currentPrice;

        return $this;
    }

    public function getMinQty(): float
    {
        return $this->minQty;
    }

    public function setMinQty(float $minQty): static
    {
        $this->minQty = $minQty;

        return $this;
    }

    public function getStepSize(): float
    {
        return $this->stepSize;
    }

    public function setStepSize(float $stepSize): static
    {
        $this->stepSize = $stepSize;

        return $this;
    }

    public function getPrecision(): int
    {
        return $this->precision;
    }

    public function setPrecision(int $precision): static
    {
        $this->precision = $precision;

        return $this;
    }

    public function getBaseAsset(): string
    {
        return $this->baseAsset;
    }

    public function setBaseAsset(string $baseAsset): static
    {
        $this->baseAsset = $baseAsset;

        return $this;
    }

    public function getQuoteAsset(): string
    {
        return $this->quoteAsset;
    }

    public function setQuoteAsset(string $quoteAsset): static
    {
        $this->quoteAsset = $quoteAsset;

        return $this;
    }

    public function getBaseAssetAvailable(): float
    {
        return $this->baseAssetAvailable;
    }

    public function setBaseAssetAvailable(float $baseAssetAvailable): static
    {
        $this->baseAssetAvailable = $baseAssetAvailable;

        return $this;
    }

    public function getQuoteAssetAvailable(): float
    {
        return $this->quoteAssetAvailable;
    }

    public function setQuoteAssetAvailable(float $quoteAssetAvailable): static
    {
        $this->quoteAssetAvailable = $quoteAssetAvailable;

        return $this;
    }

    public function getQuantityToBuy(): float
    {
        return $this->quantityToBuy;
    }

    public function setQuantityToBuy(float $quantityToBuy): static
    {
        $this->quantityToBuy = $quantityToBuy;

        return $this;
    }

    public function getQuoteAssetToBuy(): float
    {
        return $this->quoteAssetToBuy;
    }

    public function setQuoteAssetToBuy(float $quoteAssetToBuy): static
    {
        $this->quoteAssetToBuy = $quoteAssetToBuy;

        return $this;
    }

    public function getQuantityToSell(): float
    {
        return $this->quantityToSell;
    }

    public function setQuantityToSell(float $quantityToSell): static
    {
        $this->quantityToSell = $quantityToSell;

        return $this;
    }

    public function getPercentageToSpend(): float
    {
        return $this->percentageToSpend;
    }

    public function setPercentageToSpend(float $percentageToSpend): static
    {
        $this->percentageToSpend = $percentageToSpend;

        return $this;
    }

    public function getLastBuyTradePrice(): float
    {
        return $this->lastBuyTradePrice;
    }

    public function setLastBuyTradePrice(float $lastBuyTradePrice): static
    {
        $this->lastBuyTradePrice = $lastBuyTradePrice;

        return $this;
    }

    public function getLastSellTradePrice(): float
    {
        return $this->lastSellTradePrice;
    }

    public function setLastSellTradePrice(float $lastSellTradePrice): static
    {
        $this->lastSellTradePrice = $lastSellTradePrice;

        return $this;
    }
}
