<?php

/**
 * Generated by "dto:generate" command
 */

namespace App\DTO;

class IndicatorDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected string $indicator_name;
    protected \App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface $indicator;
    protected array $indicatorConfig;
    protected \App\EntityBuilder\EntityBuilderBase $builder;
    protected ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface $prev_entity;
    protected array $indicator_dependencies;

    public function getIndicatorName(): string
    {
        return $this->indicator_name;
    }

    public function setIndicatorName(string $indicator_name): static
    {
        $this->indicator_name = $indicator_name;

        return $this;
    }

    public function getIndicator(): \App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface
    {
        return $this->indicator;
    }

    public function setIndicator(\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface $indicator): static
    {
        $this->indicator = $indicator;

        return $this;
    }

    public function getIndicatorConfig(): array
    {
        return $this->indicatorConfig;
    }

    public function setIndicatorConfig(array $indicatorConfig): static
    {
        $this->indicatorConfig = $indicatorConfig;

        return $this;
    }

    public function getBuilder(): \App\EntityBuilder\EntityBuilderBase
    {
        return $this->builder;
    }

    public function setBuilder(\App\EntityBuilder\EntityBuilderBase $builder): static
    {
        $this->builder = $builder;

        return $this;
    }

    public function getPrevEntity(): ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface
    {
        return $this->prev_entity;
    }

    public function setPrevEntity(
        ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface $prev_entity,
    ): static {
        $this->prev_entity = $prev_entity;

        return $this;
    }

    public function getIndicatorDependencies(): array
    {
        return $this->indicator_dependencies;
    }

    public function setIndicatorDependencies(array $indicator_dependencies): static
    {
        $this->indicator_dependencies = $indicator_dependencies;

        return $this;
    }
}
