<?php

/**
 * Generated by "dto:generate" command
 */

declare(strict_types=1);

namespace App\DTO;

class IndicatorDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected string $indicator_name;
    protected \App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface $indicator;
    protected array $indicatorConfig;
    protected \App\EntityBuilder\EntityBuilderBase $builder;
    protected ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface $prev_entity = null;
    protected ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface $outdated_entity = null;
    protected array $indicator_dependencies;

    public function __construct(
        ?string $indicatorName = null,
        ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface $indicator = null,
        ?array $indicatorConfig = null,
        ?\App\EntityBuilder\EntityBuilderBase $builder = null,
        ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface $prevEntity = null,
        ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface $outdatedEntity = null,
        ?array $indicatorDependencies = null,
    ) {
        if ($indicatorName !== null) $this->indicator_name = $indicatorName;
        if ($indicator !== null) $this->indicator = $indicator;
        if ($indicatorConfig !== null) $this->indicatorConfig = $indicatorConfig;
        if ($builder !== null) $this->builder = $builder;
        if ($prevEntity !== null) $this->prev_entity = $prevEntity;
        if ($outdatedEntity !== null) $this->outdated_entity = $outdatedEntity;
        if ($indicatorDependencies !== null) $this->indicator_dependencies = $indicatorDependencies;
    }

    public function getIndicatorName(): string
    {
        return $this->indicator_name;
    }

    public function setIndicatorName(string $indicator_name): static
    {
        $this->indicator_name = $indicator_name;

        return $this;
    }

    public function getIndicator(): \App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface
    {
        return $this->indicator;
    }

    public function setIndicator(\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorInterface $indicator): static
    {
        $this->indicator = $indicator;

        return $this;
    }

    public function getIndicatorConfig(): array
    {
        return $this->indicatorConfig;
    }

    public function setIndicatorConfig(array $indicatorConfig): static
    {
        $this->indicatorConfig = $indicatorConfig;

        return $this;
    }

    public function getBuilder(): \App\EntityBuilder\EntityBuilderBase
    {
        return $this->builder;
    }

    public function setBuilder(\App\EntityBuilder\EntityBuilderBase $builder): static
    {
        $this->builder = $builder;

        return $this;
    }

    public function getPrevEntity(): ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface
    {
        return $this->prev_entity;
    }

    public function setPrevEntity(
        ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface $prev_entity,
    ): static {
        $this->prev_entity = $prev_entity;

        return $this;
    }

    public function getOutdatedEntity(): ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface
    {
        return $this->outdated_entity;
    }

    public function setOutdatedEntity(
        ?\App\Kstrwbry\BinanceTraderBundle\Interfaces\IndicatorEntityInterface $outdated_entity,
    ): static {
        $this->outdated_entity = $outdated_entity;

        return $this;
    }

    public function getIndicatorDependencies(): array
    {
        return $this->indicator_dependencies;
    }

    public function setIndicatorDependencies(array $indicator_dependencies): static
    {
        $this->indicator_dependencies = $indicator_dependencies;

        return $this;
    }
}
