<?php

/**
 * Generated by "dto:generate" command
 */

declare(strict_types=1);

namespace App\DTO;

class KlinerawDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected int $run_index;
    protected string $start_time;
    protected \DateTime $start_time_date;
    protected string $close_time;
    protected \DateTime $close_time_date;
    protected string $symbol;
    protected string $interval;
    protected string $first_trade_id;
    protected string $last_trade_id;
    protected string $open;
    protected float $open_float;
    protected string $close;
    protected float $close_float;
    protected string $high;
    protected float $high_float;
    protected string $low;
    protected float $low_float;
    protected string $base_asset_volume;
    protected float $base_asset_volume_float;
    protected string $trades_count;
    protected int $trades_count_int;
    protected string $is_closed;
    protected bool $is_closed_bool;
    protected string $quote_asset_volume;
    protected float $quote_asset_volume_float;
    protected string $taker_buy_base_asset_volume;
    protected float $taker_buy_base_asset_volume_float;
    protected string $taker_buy_quote_asset_volume;
    protected float $taker_buy_quote_asset_volume_float;

    public function __construct(
        ?int $runIndex = null,
        ?string $startTime = null,
        ?\DateTime $startTimeDate = null,
        ?string $closeTime = null,
        ?\DateTime $closeTimeDate = null,
        ?string $symbol = null,
        ?string $interval = null,
        ?string $firstTradeId = null,
        ?string $lastTradeId = null,
        ?string $open = null,
        ?float $openFloat = null,
        ?string $close = null,
        ?float $closeFloat = null,
        ?string $high = null,
        ?float $highFloat = null,
        ?string $low = null,
        ?float $lowFloat = null,
        ?string $baseAssetVolume = null,
        ?float $baseAssetVolumeFloat = null,
        ?string $tradesCount = null,
        ?int $tradesCountInt = null,
        ?string $isClosed = null,
        ?bool $isClosedBool = null,
        ?string $quoteAssetVolume = null,
        ?float $quoteAssetVolumeFloat = null,
        ?string $takerBuyBaseAssetVolume = null,
        ?float $takerBuyBaseAssetVolumeFloat = null,
        ?string $takerBuyQuoteAssetVolume = null,
        ?float $takerBuyQuoteAssetVolumeFloat = null,
    ) {
        if ($runIndex !== null) $this->run_index = $runIndex;
        if ($startTime !== null) $this->start_time = $startTime;
        if ($startTimeDate !== null) $this->start_time_date = $startTimeDate;
        if ($closeTime !== null) $this->close_time = $closeTime;
        if ($closeTimeDate !== null) $this->close_time_date = $closeTimeDate;
        if ($symbol !== null) $this->symbol = $symbol;
        if ($interval !== null) $this->interval = $interval;
        if ($firstTradeId !== null) $this->first_trade_id = $firstTradeId;
        if ($lastTradeId !== null) $this->last_trade_id = $lastTradeId;
        if ($open !== null) $this->open = $open;
        if ($openFloat !== null) $this->open_float = $openFloat;
        if ($close !== null) $this->close = $close;
        if ($closeFloat !== null) $this->close_float = $closeFloat;
        if ($high !== null) $this->high = $high;
        if ($highFloat !== null) $this->high_float = $highFloat;
        if ($low !== null) $this->low = $low;
        if ($lowFloat !== null) $this->low_float = $lowFloat;
        if ($baseAssetVolume !== null) $this->base_asset_volume = $baseAssetVolume;
        if ($baseAssetVolumeFloat !== null) $this->base_asset_volume_float = $baseAssetVolumeFloat;
        if ($tradesCount !== null) $this->trades_count = $tradesCount;
        if ($tradesCountInt !== null) $this->trades_count_int = $tradesCountInt;
        if ($isClosed !== null) $this->is_closed = $isClosed;
        if ($isClosedBool !== null) $this->is_closed_bool = $isClosedBool;
        if ($quoteAssetVolume !== null) $this->quote_asset_volume = $quoteAssetVolume;
        if ($quoteAssetVolumeFloat !== null) $this->quote_asset_volume_float = $quoteAssetVolumeFloat;
        if ($takerBuyBaseAssetVolume !== null) $this->taker_buy_base_asset_volume = $takerBuyBaseAssetVolume;
        if ($takerBuyBaseAssetVolumeFloat !== null) $this->taker_buy_base_asset_volume_float = $takerBuyBaseAssetVolumeFloat;
        if ($takerBuyQuoteAssetVolume !== null) $this->taker_buy_quote_asset_volume = $takerBuyQuoteAssetVolume;
        if ($takerBuyQuoteAssetVolumeFloat !== null) $this->taker_buy_quote_asset_volume_float = $takerBuyQuoteAssetVolumeFloat;
    }

    public function getRunIndex(): int
    {
        return $this->run_index;
    }

    public function setRunIndex(int $run_index): static
    {
        $this->run_index = $run_index;

        return $this;
    }

    public function getStartTime(): string
    {
        return $this->start_time;
    }

    public function setStartTime(string $start_time): static
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getStartTimeDate(): \DateTime
    {
        return $this->start_time_date;
    }

    public function setStartTimeDate(\DateTime $start_time_date): static
    {
        $this->start_time_date = $start_time_date;

        return $this;
    }

    public function getCloseTime(): string
    {
        return $this->close_time;
    }

    public function setCloseTime(string $close_time): static
    {
        $this->close_time = $close_time;

        return $this;
    }

    public function getCloseTimeDate(): \DateTime
    {
        return $this->close_time_date;
    }

    public function setCloseTimeDate(\DateTime $close_time_date): static
    {
        $this->close_time_date = $close_time_date;

        return $this;
    }

    public function getSymbol(): string
    {
        return $this->symbol;
    }

    public function setSymbol(string $symbol): static
    {
        $this->symbol = $symbol;

        return $this;
    }

    public function getInterval(): string
    {
        return $this->interval;
    }

    public function setInterval(string $interval): static
    {
        $this->interval = $interval;

        return $this;
    }

    public function getFirstTradeId(): string
    {
        return $this->first_trade_id;
    }

    public function setFirstTradeId(string $first_trade_id): static
    {
        $this->first_trade_id = $first_trade_id;

        return $this;
    }

    public function getLastTradeId(): string
    {
        return $this->last_trade_id;
    }

    public function setLastTradeId(string $last_trade_id): static
    {
        $this->last_trade_id = $last_trade_id;

        return $this;
    }

    public function getOpen(): string
    {
        return $this->open;
    }

    public function setOpen(string $open): static
    {
        $this->open = $open;

        return $this;
    }

    public function getOpenFloat(): float
    {
        return $this->open_float;
    }

    public function setOpenFloat(float $open_float): static
    {
        $this->open_float = $open_float;

        return $this;
    }

    public function getClose(): string
    {
        return $this->close;
    }

    public function setClose(string $close): static
    {
        $this->close = $close;

        return $this;
    }

    public function getCloseFloat(): float
    {
        return $this->close_float;
    }

    public function setCloseFloat(float $close_float): static
    {
        $this->close_float = $close_float;

        return $this;
    }

    public function getHigh(): string
    {
        return $this->high;
    }

    public function setHigh(string $high): static
    {
        $this->high = $high;

        return $this;
    }

    public function getHighFloat(): float
    {
        return $this->high_float;
    }

    public function setHighFloat(float $high_float): static
    {
        $this->high_float = $high_float;

        return $this;
    }

    public function getLow(): string
    {
        return $this->low;
    }

    public function setLow(string $low): static
    {
        $this->low = $low;

        return $this;
    }

    public function getLowFloat(): float
    {
        return $this->low_float;
    }

    public function setLowFloat(float $low_float): static
    {
        $this->low_float = $low_float;

        return $this;
    }

    public function getBaseAssetVolume(): string
    {
        return $this->base_asset_volume;
    }

    public function setBaseAssetVolume(string $base_asset_volume): static
    {
        $this->base_asset_volume = $base_asset_volume;

        return $this;
    }

    public function getBaseAssetVolumeFloat(): float
    {
        return $this->base_asset_volume_float;
    }

    public function setBaseAssetVolumeFloat(float $base_asset_volume_float): static
    {
        $this->base_asset_volume_float = $base_asset_volume_float;

        return $this;
    }

    public function getTradesCount(): string
    {
        return $this->trades_count;
    }

    public function setTradesCount(string $trades_count): static
    {
        $this->trades_count = $trades_count;

        return $this;
    }

    public function getTradesCountInt(): int
    {
        return $this->trades_count_int;
    }

    public function setTradesCountInt(int $trades_count_int): static
    {
        $this->trades_count_int = $trades_count_int;

        return $this;
    }

    public function getIsClosed(): string
    {
        return $this->is_closed;
    }

    public function setIsClosed(string $is_closed): static
    {
        $this->is_closed = $is_closed;

        return $this;
    }

    public function getIsClosedBool(): bool
    {
        return $this->is_closed_bool;
    }

    public function setIsClosedBool(bool $is_closed_bool): static
    {
        $this->is_closed_bool = $is_closed_bool;

        return $this;
    }

    public function getQuoteAssetVolume(): string
    {
        return $this->quote_asset_volume;
    }

    public function setQuoteAssetVolume(string $quote_asset_volume): static
    {
        $this->quote_asset_volume = $quote_asset_volume;

        return $this;
    }

    public function getQuoteAssetVolumeFloat(): float
    {
        return $this->quote_asset_volume_float;
    }

    public function setQuoteAssetVolumeFloat(float $quote_asset_volume_float): static
    {
        $this->quote_asset_volume_float = $quote_asset_volume_float;

        return $this;
    }

    public function getTakerBuyBaseAssetVolume(): string
    {
        return $this->taker_buy_base_asset_volume;
    }

    public function setTakerBuyBaseAssetVolume(string $taker_buy_base_asset_volume): static
    {
        $this->taker_buy_base_asset_volume = $taker_buy_base_asset_volume;

        return $this;
    }

    public function getTakerBuyBaseAssetVolumeFloat(): float
    {
        return $this->taker_buy_base_asset_volume_float;
    }

    public function setTakerBuyBaseAssetVolumeFloat(float $taker_buy_base_asset_volume_float): static
    {
        $this->taker_buy_base_asset_volume_float = $taker_buy_base_asset_volume_float;

        return $this;
    }

    public function getTakerBuyQuoteAssetVolume(): string
    {
        return $this->taker_buy_quote_asset_volume;
    }

    public function setTakerBuyQuoteAssetVolume(string $taker_buy_quote_asset_volume): static
    {
        $this->taker_buy_quote_asset_volume = $taker_buy_quote_asset_volume;

        return $this;
    }

    public function getTakerBuyQuoteAssetVolumeFloat(): float
    {
        return $this->taker_buy_quote_asset_volume_float;
    }

    public function setTakerBuyQuoteAssetVolumeFloat(float $taker_buy_quote_asset_volume_float): static
    {
        $this->taker_buy_quote_asset_volume_float = $taker_buy_quote_asset_volume_float;

        return $this;
    }
}
