<?php

/**
 * Generated by "dto:generate" command
 */

declare(strict_types=1);

namespace App\DTO;

class MacdDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected int $short_period;
    protected int $long_period;
    protected int $signal_period;

    public function __construct(?int $shortPeriod = null, ?int $longPeriod = null, ?int $signalPeriod = null)
    {
        if ($shortPeriod !== null) $this->short_period = $shortPeriod;
        if ($longPeriod !== null) $this->long_period = $longPeriod;
        if ($signalPeriod !== null) $this->signal_period = $signalPeriod;
    }

    public function getShortPeriod(): int
    {
        return $this->short_period;
    }

    public function setShortPeriod(int $short_period): static
    {
        $this->short_period = $short_period;

        return $this;
    }

    public function getLongPeriod(): int
    {
        return $this->long_period;
    }

    public function setLongPeriod(int $long_period): static
    {
        $this->long_period = $long_period;

        return $this;
    }

    public function getSignalPeriod(): int
    {
        return $this->signal_period;
    }

    public function setSignalPeriod(int $signal_period): static
    {
        $this->signal_period = $signal_period;

        return $this;
    }
}
