<?php

/**
 * Generated by "dto:generate" command
 */

namespace App\DTO;

class MacdDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected int $short_period;
    protected int $long_period;
    protected int $signal_period;

    public function getShortPeriod(): int
    {
        return $this->short_period;
    }

    public function setShortPeriod(int $short_period): static
    {
        $this->short_period = $short_period;

        return $this;
    }

    public function getLongPeriod(): int
    {
        return $this->long_period;
    }

    public function setLongPeriod(int $long_period): static
    {
        $this->long_period = $long_period;

        return $this;
    }

    public function getSignalPeriod(): int
    {
        return $this->signal_period;
    }

    public function setSignalPeriod(int $signal_period): static
    {
        $this->signal_period = $signal_period;

        return $this;
    }
}
