<?php

/**
 * Generated by "dto:generate" command
 */

declare(strict_types=1);

namespace App\DTO;

class RviDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected int $period;
    protected int $lower_signal_line;
    protected int $upper_signal_line;

    public function __construct(?int $period = null, ?int $lowerSignalLine = null, ?int $upperSignalLine = null)
    {
        if ($period !== null) $this->period = $period;
        if ($lowerSignalLine !== null) $this->lower_signal_line = $lowerSignalLine;
        if ($upperSignalLine !== null) $this->upper_signal_line = $upperSignalLine;
    }

    public function getPeriod(): int
    {
        return $this->period;
    }

    public function setPeriod(int $period): static
    {
        $this->period = $period;

        return $this;
    }

    public function getLowerSignalLine(): int
    {
        return $this->lower_signal_line;
    }

    public function setLowerSignalLine(int $lower_signal_line): static
    {
        $this->lower_signal_line = $lower_signal_line;

        return $this;
    }

    public function getUpperSignalLine(): int
    {
        return $this->upper_signal_line;
    }

    public function setUpperSignalLine(int $upper_signal_line): static
    {
        $this->upper_signal_line = $upper_signal_line;

        return $this;
    }
}
