<?php

/**
 * Generated by "dto:generate" command
 */

namespace App\DTO;

class StddevDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected int $period;

    public function getPeriod(): int
    {
        return $this->period;
    }

    public function setPeriod(int $period): static
    {
        $this->period = $period;

        return $this;
    }
}
