<?php

/**
 * Generated by "dto:generate" command
 */

declare(strict_types=1);

namespace App\DTO;

class StrategyDTO extends \App\Kstrwbry\DtoBundle\Base\DtoBase
{
    protected string $strategy_name;
    protected int $stop_loss_condition;
    protected array $indicators;

    public function __construct(
        ?string $strategyName = null,
        ?int $stopLossCondition = null,
        ?array $indicators = null,
    ) {
        if ($strategyName !== null) $this->strategy_name = $strategyName;
        if ($stopLossCondition !== null) $this->stop_loss_condition = $stopLossCondition;
        if ($indicators !== null) $this->indicators = $indicators;
    }

    public function getStrategyName(): string
    {
        return $this->strategy_name;
    }

    public function setStrategyName(string $strategy_name): static
    {
        $this->strategy_name = $strategy_name;

        return $this;
    }

    public function getStopLossCondition(): int
    {
        return $this->stop_loss_condition;
    }

    public function setStopLossCondition(int $stop_loss_condition): static
    {
        $this->stop_loss_condition = $stop_loss_condition;

        return $this;
    }

    public function getIndicators(): array
    {
        return $this->indicators;
    }

    public function setIndicators(array $indicators): static
    {
        $this->indicators = $indicators;

        return $this;
    }
}
