<?php
declare(strict_types=1);

namespace App\Kstrwbry\DtoBundle\Command;

use App\Kstrwbry\DtoBundle\Builder\DtoClassBuilder;
use Nette\PhpGenerator\PsrPrinter;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'dto:generate',
    description: 'Generates DTO classes from YAML definitions'
)]
class GenerateDtoCommand extends Command
{
    public const string SCOPE_NAME = 'DTO';

    private string $outputDir;

    private array $dtoDefinitions;

    #private InputInterface $input;

    private OutputInterface $output;

    private string $namespace;

    private PsrPrinter $psrPrinter;

    public function __construct(string $appDir, string $namespace, array $dtoDefinitions)
    {
        parent::__construct();

        $this->outputDir = sprintf('%s/%s', $appDir, static::SCOPE_NAME);
        $this->dtoDefinitions = $dtoDefinitions;
        $this->namespace = sprintf('%s\%s', $namespace, static::SCOPE_NAME);
        $this->psrPrinter = new PsrPrinter();
    }

    protected function execute(
        InputInterface $input,
        OutputInterface $output,
        ): int {
        $this->output = $output;

        $this->clearOutputDirectory();
        $this->createOutputDirectory();

        $this->createDtoClasses();

        return Command::SUCCESS;
    }


    protected function clearOutputDirectory(): void
    {
        if (!is_dir($this->outputDir)) {
            return;
        }

        $files = glob($this->outputDir . '/*');
        if ($files) {
            foreach ($files as $file) {
                if (is_file($file)) {
                    unlink($file);
                }
            }
        }
    }

    private function createOutputDirectory(): void
    {
        if (!is_dir($this->outputDir)) {
            mkdir($this->outputDir, 0777, true);
        }
    }

    private function createDtoClasses(): void
    {
        foreach ($this->dtoDefinitions['dto_definitions'] as $baseName => $definition) {
            $this->createDtoClass($baseName, $definition);
        }


        $this->output->writeln(sprintf(
            '<info>"%s" classes generated in "%s"</info>',
            static::SCOPE_NAME,
            $this->outputDir,
        ));
    }

    private function createDtoClass(string $baseName, array $definition): void
    {
        $className = ucfirst(strtolower($baseName)) . static::SCOPE_NAME;

        $file = new DtoClassBuilder(
            $className,
            $this->namespace,
            $definition,
        )->build();

        $file->addComment(sprintf('Generated by "%s" command', $this->getName()));

        file_put_contents(
            sprintf('%s/%s.php', $this->outputDir, $className),
            $this->psrPrinter->printFile($file),
        );
    }
}
